// 从内置浏览器的持久会话导出登录 Cookie（Netscape 格式），供 yt-dlp 使用
// 用法：在"浏览器"页签登录站点后，下载该站点 URL 时自动携带登录态
const fs = require('fs');
const os = require('os');
const path = require('path');

let cookieSession = null;

function setSession(s) { cookieSession = s; }

function toNetscape(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by OpenTube', ''];
  for (const c of cookies) {
    const domain = c.domain || '';
    const flag = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push([domain, flag, c.path || '/', c.secure ? 'TRUE' : 'FALSE', expiry, c.name, c.value].join('\t'));
  }
  return lines.join('\n') + '\n';
}

// 导出指定 URL 匹配的 Cookie 到临时文件，返回文件路径；无 Cookie 返回 null
async function exportFor(url) {
  if (!cookieSession || !url) return null;
  if (!/^https?:\/\//i.test(url)) return null;
  let host;
  try { host = new URL(url).hostname; } catch (_) { return null; }
  let cookies;
  try { cookies = await cookieSession.cookies.get({ url }); } catch (_) { return null; }
  if (!cookies.length) return null;
  const file = path.join(os.tmpdir(), 'opentube-cookies.txt');
  fs.writeFileSync(file, toNetscape(cookies));
  console.log(`[opentube] cookies: ${cookies.length} 条 -> ${file} (${host})`);
  return file;
}

module.exports = { setSession, exportFor };
